### ISSUE TITLE
Use MIT license in the correct way

### ISSUE THREAD

**Issue by AnimiVulpis** [signavio/eslint-config-signavio#3]
In the currently existing `LICENCE` file the **copyright holder(s)** are missing.

See: http://choosealicense.com/licenses/mit/

**Comment by frontendphil** [comment]
@AnimiVulpis you fancy creating a PR?

**Comment by AnimiVulpis** [comment]
Ok. 
Will do. 
But don't expect it before the weekend 😜

**Comment by jbreckel** [comment]
ping, weekend over? ;)

**Comment by jbreckel** [comment]
Closed with #7
